// This is auto-generated, do not edit!
#include "jdf.h"
#ifndef HTTP_CODES_JSON
#define HTTP_CODES_JSON
enum http_method {
  INVALID_HTTP_METHOD,
  GET,
  HEAD,
  POST,
  PUT,
  DELETE,
  CONNECT,
  OPTIONS,
  TRACE,
  PATCH,
};
const char *spell_http_method[] = {
  [GET] = "GET",
  [HEAD] = "HEAD",
  [POST] = "POST",
  [PUT] = "PUT",
  [DELETE] = "DELETE",
  [CONNECT] = "CONNECT",
  [OPTIONS] = "OPTIONS",
  [TRACE] = "TRACE",
  [PATCH] = "PATCH",
};
const char *describe_http_method[] = {
  [GET] = "The GET method requests a representation of the specified resource. Requests using GET should only retrieve data and should not contain a request content.",
  [HEAD] = "The HEAD method asks for a response identical to a GET request, but without a response body.",
  [POST] = "The POST method submits an entity to the specified resource, often causing a change in state or side effects on the server.",
  [PUT] = "The PUT method replaces all current representations of the target resource with the request content.",
  [DELETE] = "The DELETE method deletes the specified resource.",
  [CONNECT] = "The CONNECT method establishes a tunnel to the server identified by the target resource.",
  [OPTIONS] = "The OPTIONS method describes the communication options for the target resource.",
  [TRACE] = "The TRACE method performs a message loop-back test along the path to the target resource.",
  [PATCH] = "The PATCH method applies partial modifications to a resource.",
};
enum http_method parse_http_method(s8 s) {
  for (size i = 0; i < 9; i++)
    if(s8equal(s, s8wrap(spell_http_method[i], 1024)))
      return (enum http_method)i;
  return (enum http_method)0;
}
enum http_status {
  INVALID_HTTP_STATUS,
  CONTINUE = 100,
  SWITCHING_PROTOCOLS = 101,
  PROCESSING = 102,
  EARLY_HINTS = 103,
  OK = 200,
  CREATED = 201,
  ACCEPTED = 202,
  NON_AUTHORITATIVE_INFORMATION = 203,
  NO_CONTENT = 204,
  RESET_CONTENT = 205,
  PARTIAL_CONTENT = 206,
  MULTI_STATUS = 207,
  ALREADY_REPORTED = 208,
  THIS_IS_FINE__APACHE_WEB_SERVER_ = 218,
  IM_USED = 226,
  MULTIPLE_CHOICES = 300,
  MOVED_PERMANENTLY = 301,
  FOUND = 302,
  SEE_OTHER = 303,
  NOT_MODIFIED = 304,
  SWITCH_PROXY = 306,
  TEMPORARY_REDIRECT = 307,
  RESUME_INCOMPLETE = 308,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  PAYMENT_REQUIRED = 402,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  METHOD_NOT_ALLOWED = 405,
  NOT_ACCEPTABLE = 406,
  PROXY_AUTHENTICATION_REQUIRED = 407,
  REQUEST_TIMEOUT = 408,
  CONFLICT = 409,
  GONE = 410,
  LENGTH_REQUIRED = 411,
  PRECONDITION_FAILED = 412,
  REQUEST_ENTITY_TOO_LARGE = 413,
  REQUEST_URI_TOO_LONG = 414,
  UNSUPPORTED_MEDIA_TYPE = 415,
  REQUESTED_RANGE_NOT_SATISFIABLE = 416,
  EXPECTATION_FAILED = 417,
  I_M_A_TEAPOT = 418,
  PAGE_EXPIRED__LARAVEL_FRAMEWORK_ = 419,
  METHOD_FAILURE__SPRING_FRAMEWORK_ = 420,
  MISDIRECTED_REQUEST = 421,
  UNPROCESSABLE_ENTITY = 422,
  LOCKED = 423,
  FAILED_DEPENDENCY = 424,
  UPGRADE_REQUIRED = 426,
  PRECONDITION_REQUIRED = 428,
  TOO_MANY_REQUESTS = 429,
  REQUEST_HEADER_FIELDS_TOO_LARGE = 431,
  LOGIN_TIME_OUT = 440,
  CONNECTION_CLOSED_WITHOUT_RESPONSE = 444,
  RETRY_WITH = 449,
  BLOCKED_BY_WINDOWS_PARENTAL_CONTROLS = 450,
  UNAVAILABLE_FOR_LEGAL_REASONS = 451,
  REQUEST_HEADER_TOO_LARGE = 494,
  SSL_CERTIFICATE_ERROR = 495,
  SSL_CERTIFICATE_REQUIRED = 496,
  HTTP_REQUEST_SENT_TO_HTTPS_PORT = 497,
  INVALID_TOKEN__ESRI_ = 498,
  CLIENT_CLOSED_REQUEST = 499,
  INTERNAL_SERVER_ERROR = 500,
  NOT_IMPLEMENTED = 501,
  BAD_GATEWAY = 502,
  SERVICE_UNAVAILABLE = 503,
  GATEWAY_TIMEOUT = 504,
  HTTP_VERSION_NOT_SUPPORTED = 505,
  VARIANT_ALSO_NEGOTIATES = 506,
  INSUFFICIENT_STORAGE = 507,
  LOOP_DETECTED = 508,
  BANDWIDTH_LIMIT_EXCEEDED = 509,
  NOT_EXTENDED = 510,
  NETWORK_AUTHENTICATION_REQUIRED = 511,
  UNKNOWN_ERROR = 520,
  WEB_SERVER_IS_DOWN = 521,
  CONNECTION_TIMED_OUT = 522,
  ORIGIN_IS_UNREACHABLE = 523,
  A_TIMEOUT_OCCURRED = 524,
  SSL_HANDSHAKE_FAILED = 525,
  INVALID_SSL_CERTIFICATE = 526,
  RAILGUN_LISTENER_TO_ORIGIN_ERROR = 527,
  ORIGIN_DNS_ERROR = 530,
  NETWORK_READ_TIMEOUT_ERROR = 598,
};
const char *spell_http_status[] = {
  [CONTINUE] = "Continue",
  [SWITCHING_PROTOCOLS] = "Switching Protocols",
  [PROCESSING] = "Processing",
  [EARLY_HINTS] = "Early Hints",
  [OK] = "OK",
  [CREATED] = "Created",
  [ACCEPTED] = "Accepted",
  [NON_AUTHORITATIVE_INFORMATION] = "Non-Authoritative Information",
  [NO_CONTENT] = "No Content",
  [RESET_CONTENT] = "Reset Content",
  [PARTIAL_CONTENT] = "Partial Content",
  [MULTI_STATUS] = "Multi-Status",
  [ALREADY_REPORTED] = "Already Reported",
  [THIS_IS_FINE__APACHE_WEB_SERVER_] = "This is fine (Apache Web Server)",
  [IM_USED] = "IM Used",
  [MULTIPLE_CHOICES] = "Multiple Choices",
  [MOVED_PERMANENTLY] = "Moved Permanently",
  [FOUND] = "Found",
  [SEE_OTHER] = "See Other",
  [NOT_MODIFIED] = "Not Modified",
  [SWITCH_PROXY] = "Switch Proxy",
  [TEMPORARY_REDIRECT] = "Temporary Redirect",
  [RESUME_INCOMPLETE] = "Resume Incomplete",
  [BAD_REQUEST] = "Bad Request",
  [UNAUTHORIZED] = "Unauthorized",
  [PAYMENT_REQUIRED] = "Payment Required",
  [FORBIDDEN] = "Forbidden",
  [NOT_FOUND] = "Not Found",
  [METHOD_NOT_ALLOWED] = "Method Not Allowed",
  [NOT_ACCEPTABLE] = "Not Acceptable",
  [PROXY_AUTHENTICATION_REQUIRED] = "Proxy Authentication Required",
  [REQUEST_TIMEOUT] = "Request Timeout",
  [CONFLICT] = "Conflict",
  [GONE] = "Gone",
  [LENGTH_REQUIRED] = "Length Required",
  [PRECONDITION_FAILED] = "Precondition Failed",
  [REQUEST_ENTITY_TOO_LARGE] = "Request Entity Too Large",
  [REQUEST_URI_TOO_LONG] = "Request-URI Too Long",
  [UNSUPPORTED_MEDIA_TYPE] = "Unsupported Media Type",
  [REQUESTED_RANGE_NOT_SATISFIABLE] = "Requested Range Not Satisfiable",
  [EXPECTATION_FAILED] = "Expectation Failed",
  [I_M_A_TEAPOT] = "I'm a teapot",
  [PAGE_EXPIRED__LARAVEL_FRAMEWORK_] = "Page Expired (Laravel Framework)",
  [METHOD_FAILURE__SPRING_FRAMEWORK_] = "Method Failure (Spring Framework)",
  [MISDIRECTED_REQUEST] = "Misdirected Request",
  [UNPROCESSABLE_ENTITY] = "Unprocessable Entity",
  [LOCKED] = "Locked",
  [FAILED_DEPENDENCY] = "Failed Dependency",
  [UPGRADE_REQUIRED] = "Upgrade Required",
  [PRECONDITION_REQUIRED] = "Precondition Required",
  [TOO_MANY_REQUESTS] = "Too Many Requests",
  [REQUEST_HEADER_FIELDS_TOO_LARGE] = "Request Header Fields Too Large",
  [LOGIN_TIME_OUT] = "Login Time-out",
  [CONNECTION_CLOSED_WITHOUT_RESPONSE] = "Connection Closed Without Response",
  [RETRY_WITH] = "Retry With",
  [BLOCKED_BY_WINDOWS_PARENTAL_CONTROLS] = "Blocked by Windows Parental Controls",
  [UNAVAILABLE_FOR_LEGAL_REASONS] = "Unavailable For Legal Reasons",
  [REQUEST_HEADER_TOO_LARGE] = "Request Header Too Large",
  [SSL_CERTIFICATE_ERROR] = "SSL Certificate Error",
  [SSL_CERTIFICATE_REQUIRED] = "SSL Certificate Required",
  [HTTP_REQUEST_SENT_TO_HTTPS_PORT] = "HTTP Request Sent to HTTPS Port",
  [INVALID_TOKEN__ESRI_] = "Invalid Token (Esri)",
  [CLIENT_CLOSED_REQUEST] = "Client Closed Request",
  [INTERNAL_SERVER_ERROR] = "Internal Server Error",
  [NOT_IMPLEMENTED] = "Not Implemented",
  [BAD_GATEWAY] = "Bad Gateway",
  [SERVICE_UNAVAILABLE] = "Service Unavailable",
  [GATEWAY_TIMEOUT] = "Gateway Timeout",
  [HTTP_VERSION_NOT_SUPPORTED] = "HTTP Version Not Supported",
  [VARIANT_ALSO_NEGOTIATES] = "Variant Also Negotiates",
  [INSUFFICIENT_STORAGE] = "Insufficient Storage",
  [LOOP_DETECTED] = "Loop Detected",
  [BANDWIDTH_LIMIT_EXCEEDED] = "Bandwidth Limit Exceeded",
  [NOT_EXTENDED] = "Not Extended",
  [NETWORK_AUTHENTICATION_REQUIRED] = "Network Authentication Required",
  [UNKNOWN_ERROR] = "Unknown Error",
  [WEB_SERVER_IS_DOWN] = "Web Server Is Down",
  [CONNECTION_TIMED_OUT] = "Connection Timed Out",
  [ORIGIN_IS_UNREACHABLE] = "Origin Is Unreachable",
  [A_TIMEOUT_OCCURRED] = "A Timeout Occurred",
  [SSL_HANDSHAKE_FAILED] = "SSL Handshake Failed",
  [INVALID_SSL_CERTIFICATE] = "Invalid SSL Certificate",
  [RAILGUN_LISTENER_TO_ORIGIN_ERROR] = "Railgun Listener to Origin Error",
  [ORIGIN_DNS_ERROR] = "Origin DNS Error",
  [NETWORK_READ_TIMEOUT_ERROR] = "Network Read Timeout Error",
};
const char *describe_http_status[] = {
  [CONTINUE] = "Continue",
  [SWITCHING_PROTOCOLS] = "Switching Protocols",
  [PROCESSING] = "Processing",
  [EARLY_HINTS] = "Early Hints",
  [OK] = "OK",
  [CREATED] = "Created",
  [ACCEPTED] = "Accepted",
  [NON_AUTHORITATIVE_INFORMATION] = "Non-Authoritative Information",
  [NO_CONTENT] = "No Content",
  [RESET_CONTENT] = "Reset Content",
  [PARTIAL_CONTENT] = "Partial Content",
  [MULTI_STATUS] = "Multi-Status",
  [ALREADY_REPORTED] = "Already Reported",
  [THIS_IS_FINE__APACHE_WEB_SERVER_] = "This is fine (Apache Web Server)",
  [IM_USED] = "IM Used",
  [MULTIPLE_CHOICES] = "Multiple Choices",
  [MOVED_PERMANENTLY] = "Moved Permanently",
  [FOUND] = "Found",
  [SEE_OTHER] = "See Other",
  [NOT_MODIFIED] = "Not Modified",
  [SWITCH_PROXY] = "Switch Proxy",
  [TEMPORARY_REDIRECT] = "Temporary Redirect",
  [RESUME_INCOMPLETE] = "Resume Incomplete",
  [BAD_REQUEST] = "Bad Request",
  [UNAUTHORIZED] = "Unauthorized",
  [PAYMENT_REQUIRED] = "Payment Required",
  [FORBIDDEN] = "Forbidden",
  [NOT_FOUND] = "Not Found",
  [METHOD_NOT_ALLOWED] = "Method Not Allowed",
  [NOT_ACCEPTABLE] = "Not Acceptable",
  [PROXY_AUTHENTICATION_REQUIRED] = "Proxy Authentication Required",
  [REQUEST_TIMEOUT] = "Request Timeout",
  [CONFLICT] = "Conflict",
  [GONE] = "Gone",
  [LENGTH_REQUIRED] = "Length Required",
  [PRECONDITION_FAILED] = "Precondition Failed",
  [REQUEST_ENTITY_TOO_LARGE] = "Request Entity Too Large",
  [REQUEST_URI_TOO_LONG] = "Request-URI Too Long",
  [UNSUPPORTED_MEDIA_TYPE] = "Unsupported Media Type",
  [REQUESTED_RANGE_NOT_SATISFIABLE] = "Requested Range Not Satisfiable",
  [EXPECTATION_FAILED] = "Expectation Failed",
  [I_M_A_TEAPOT] = "I'm a teapot",
  [PAGE_EXPIRED__LARAVEL_FRAMEWORK_] = "Page Expired (Laravel Framework)",
  [METHOD_FAILURE__SPRING_FRAMEWORK_] = "Method Failure (Spring Framework)",
  [MISDIRECTED_REQUEST] = "Misdirected Request",
  [UNPROCESSABLE_ENTITY] = "Unprocessable Entity",
  [LOCKED] = "Locked",
  [FAILED_DEPENDENCY] = "Failed Dependency",
  [UPGRADE_REQUIRED] = "Upgrade Required",
  [PRECONDITION_REQUIRED] = "Precondition Required",
  [TOO_MANY_REQUESTS] = "Too Many Requests",
  [REQUEST_HEADER_FIELDS_TOO_LARGE] = "Request Header Fields Too Large",
  [LOGIN_TIME_OUT] = "Login Time-out",
  [CONNECTION_CLOSED_WITHOUT_RESPONSE] = "Connection Closed Without Response",
  [RETRY_WITH] = "Retry With",
  [BLOCKED_BY_WINDOWS_PARENTAL_CONTROLS] = "Blocked by Windows Parental Controls",
  [UNAVAILABLE_FOR_LEGAL_REASONS] = "Unavailable For Legal Reasons",
  [REQUEST_HEADER_TOO_LARGE] = "Request Header Too Large",
  [SSL_CERTIFICATE_ERROR] = "SSL Certificate Error",
  [SSL_CERTIFICATE_REQUIRED] = "SSL Certificate Required",
  [HTTP_REQUEST_SENT_TO_HTTPS_PORT] = "HTTP Request Sent to HTTPS Port",
  [INVALID_TOKEN__ESRI_] = "Invalid Token (Esri)",
  [CLIENT_CLOSED_REQUEST] = "Client Closed Request",
  [INTERNAL_SERVER_ERROR] = "Internal Server Error",
  [NOT_IMPLEMENTED] = "Not Implemented",
  [BAD_GATEWAY] = "Bad Gateway",
  [SERVICE_UNAVAILABLE] = "Service Unavailable",
  [GATEWAY_TIMEOUT] = "Gateway Timeout",
  [HTTP_VERSION_NOT_SUPPORTED] = "HTTP Version Not Supported",
  [VARIANT_ALSO_NEGOTIATES] = "Variant Also Negotiates",
  [INSUFFICIENT_STORAGE] = "Insufficient Storage",
  [LOOP_DETECTED] = "Loop Detected",
  [BANDWIDTH_LIMIT_EXCEEDED] = "Bandwidth Limit Exceeded",
  [NOT_EXTENDED] = "Not Extended",
  [NETWORK_AUTHENTICATION_REQUIRED] = "Network Authentication Required",
  [UNKNOWN_ERROR] = "Unknown Error",
  [WEB_SERVER_IS_DOWN] = "Web Server Is Down",
  [CONNECTION_TIMED_OUT] = "Connection Timed Out",
  [ORIGIN_IS_UNREACHABLE] = "Origin Is Unreachable",
  [A_TIMEOUT_OCCURRED] = "A Timeout Occurred",
  [SSL_HANDSHAKE_FAILED] = "SSL Handshake Failed",
  [INVALID_SSL_CERTIFICATE] = "Invalid SSL Certificate",
  [RAILGUN_LISTENER_TO_ORIGIN_ERROR] = "Railgun Listener to Origin Error",
  [ORIGIN_DNS_ERROR] = "Origin DNS Error",
  [NETWORK_READ_TIMEOUT_ERROR] = "Network Read Timeout Error",
};
enum http_status parse_http_status(s8 s) {
  for (size i = 0; i < 85; i++)
    if(s8equal(s, s8wrap(spell_http_status[i], 1024)))
      return (enum http_status)i;
  return (enum http_status)0;
}
enum content_type {
  INVALID_CONTENT_TYPE,
  HTML,
};
const char *spell_content_type[] = {
  [HTML] = "html",
};
const char *describe_content_type[] = {
  [HTML] = "text/html; charset=UTF-8",
};
enum content_type parse_content_type(s8 s) {
  for (size i = 0; i < 1; i++)
    if(s8equal(s, s8wrap(spell_content_type[i], 1024)))
      return (enum content_type)i;
  return (enum content_type)0;
}
#endif // HTTP_CODES_JSON
