// This is auto-generated, do not edit!
#include "jdf.h"
#ifndef HTTP_CODES_JSON
#define HTTP_CODES_JSON
enum http_method {
  INVALID_HTTP_METHOD,
  GET,
  HEAD,
  POST,
  PUT,
  DELETE,
  CONNECT,
  OPTIONS,
  TRACE,
  PATCH,
};
const char *spell_http_method[] = {
  [GET] = "GET",
  [HEAD] = "HEAD",
  [POST] = "POST",
  [PUT] = "PUT",
  [DELETE] = "DELETE",
  [CONNECT] = "CONNECT",
  [OPTIONS] = "OPTIONS",
  [TRACE] = "TRACE",
  [PATCH] = "PATCH",
};
const char *describe_http_method[] = {
  [GET] = "The GET method requests a representation of the specified resource. Requests using GET should only retrieve data and should not contain a request content.",
  [HEAD] = "The HEAD method asks for a response identical to a GET request, but without a response body.",
  [POST] = "The POST method submits an entity to the specified resource, often causing a change in state or side effects on the server.",
  [PUT] = "The PUT method replaces all current representations of the target resource with the request content.",
  [DELETE] = "The DELETE method deletes the specified resource.",
  [CONNECT] = "The CONNECT method establishes a tunnel to the server identified by the target resource.",
  [OPTIONS] = "The OPTIONS method describes the communication options for the target resource.",
  [TRACE] = "The TRACE method performs a message loop-back test along the path to the target resource.",
  [PATCH] = "The PATCH method applies partial modifications to a resource.",
};
enum http_method parse_http_method(s8 s) {
  for (size i = 0; i < 9; i++)
    if(s8equal(s, s8wrap(spell_http_method[i], 1024)))
      return (enum http_method)i;
  return (enum http_method)0;
}
enum http_status {
  INVALID_HTTP_STATUS,
  CONTINUE = 100,
  SWITCHING_PROTOCOLS = 101,
  PROCESSING = 102,
  EARLY_HINTS = 103,
  OK = 200,
  CREATED = 201,
  ACCEPTED = 202,
  NON_AUTHORITATIVE_INFORMATION = 203,
  NO_CONTENT = 204,
  RESET_CONTENT = 205,
  PARTIAL_CONTENT = 206,
  MULTI_STATUS = 207,
  ALREADY_REPORTED = 208,
  THIS_IS_FINE__APACHE_WEB_SERVER_ = 218,
  IM_USED = 226,
  MULTIPLE_CHOICES = 300,
  MOVED_PERMANENTLY = 301,
  FOUND = 302,
  SEE_OTHER = 303,
  NOT_MODIFIED = 304,
  SWITCH_PROXY = 306,
  TEMPORARY_REDIRECT = 307,
  PERMANENT_REDIRECT = 308,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  PAYMENT_REQUIRED = 402,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  METHOD_NOT_ALLOWED = 405,
  NOT_ACCEPTABLE = 406,
  PROXY_AUTHENTICATION_REQUIRED = 407,
  REQUEST_TIMEOUT = 408,
  CONFLICT = 409,
  GONE = 410,
  LENGTH_REQUIRED = 411,
  PRECONDITION_FAILED = 412,
  CONTENT_TOO_LARGE = 413,
  URI_TOO_LONG = 414,
  UNSUPPORTED_MEDIA_TYPE = 415,
  REQUESTED_RANGE_NOT_SATISFIABLE = 416,
  EXPECTATION_FAILED = 417,
  I_M_A_TEAPOT = 418,
  PAGE_EXPIRED__LARAVEL_FRAMEWORK_ = 419,
  METHOD_FAILURE__SPRING_FRAMEWORK_ = 420,
  MISDIRECTED_REQUEST = 421,
  UNPROCESSABLE_CONTENT = 422,
  LOCKED = 423,
  FAILED_DEPENDENCY = 424,
  UPGRADE_REQUIRED = 426,
  PRECONDITION_REQUIRED = 428,
  TOO_MANY_REQUESTS = 429,
  REQUEST_HEADER_FIELDS_TOO_LARGE = 431,
  LOGIN_TIME_OUT = 440,
  CONNECTION_CLOSED_WITHOUT_RESPONSE = 444,
  RETRY_WITH = 449,
  BLOCKED_BY_WINDOWS_PARENTAL_CONTROLS = 450,
  UNAVAILABLE_FOR_LEGAL_REASONS = 451,
  REQUEST_HEADER_TOO_LARGE = 494,
  SSL_CERTIFICATE_ERROR = 495,
  SSL_CERTIFICATE_REQUIRED = 496,
  HTTP_REQUEST_SENT_TO_HTTPS_PORT = 497,
  INVALID_TOKEN__ESRI_ = 498,
  CLIENT_CLOSED_REQUEST = 499,
  INTERNAL_SERVER_ERROR = 500,
  NOT_IMPLEMENTED = 501,
  BAD_GATEWAY = 502,
  SERVICE_UNAVAILABLE = 503,
  GATEWAY_TIMEOUT = 504,
  HTTP_VERSION_NOT_SUPPORTED = 505,
  VARIANT_ALSO_NEGOTIATES = 506,
  INSUFFICIENT_STORAGE = 507,
  LOOP_DETECTED = 508,
  BANDWIDTH_LIMIT_EXCEEDED = 509,
  NOT_EXTENDED = 510,
  NETWORK_AUTHENTICATION_REQUIRED = 511,
  UNKNOWN_ERROR = 520,
  WEB_SERVER_IS_DOWN = 521,
  CONNECTION_TIMED_OUT = 522,
  ORIGIN_IS_UNREACHABLE = 523,
  A_TIMEOUT_OCCURRED = 524,
  SSL_HANDSHAKE_FAILED = 525,
  INVALID_SSL_CERTIFICATE = 526,
  RAILGUN_LISTENER_TO_ORIGIN_ERROR = 527,
  ORIGIN_DNS_ERROR = 530,
  NETWORK_READ_TIMEOUT_ERROR = 598,
};
const char *spell_http_status[] = {
  [CONTINUE] = "Continue",
  [SWITCHING_PROTOCOLS] = "Switching Protocols",
  [PROCESSING] = "Processing",
  [EARLY_HINTS] = "Early Hints",
  [OK] = "OK",
  [CREATED] = "Created",
  [ACCEPTED] = "Accepted",
  [NON_AUTHORITATIVE_INFORMATION] = "Non-Authoritative Information",
  [NO_CONTENT] = "No Content",
  [RESET_CONTENT] = "Reset Content",
  [PARTIAL_CONTENT] = "Partial Content",
  [MULTI_STATUS] = "Multi-Status",
  [ALREADY_REPORTED] = "Already Reported",
  [THIS_IS_FINE__APACHE_WEB_SERVER_] = "This is fine (Apache Web Server)",
  [IM_USED] = "IM Used",
  [MULTIPLE_CHOICES] = "Multiple Choices",
  [MOVED_PERMANENTLY] = "Moved Permanently",
  [FOUND] = "Found",
  [SEE_OTHER] = "See Other",
  [NOT_MODIFIED] = "Not Modified",
  [SWITCH_PROXY] = "Switch Proxy",
  [TEMPORARY_REDIRECT] = "Temporary Redirect",
  [PERMANENT_REDIRECT] = "Permanent Redirect",
  [BAD_REQUEST] = "Bad Request",
  [UNAUTHORIZED] = "Unauthorized",
  [PAYMENT_REQUIRED] = "Payment Required",
  [FORBIDDEN] = "Forbidden",
  [NOT_FOUND] = "Not Found",
  [METHOD_NOT_ALLOWED] = "Method Not Allowed",
  [NOT_ACCEPTABLE] = "Not Acceptable",
  [PROXY_AUTHENTICATION_REQUIRED] = "Proxy Authentication Required",
  [REQUEST_TIMEOUT] = "Request Timeout",
  [CONFLICT] = "Conflict",
  [GONE] = "Gone",
  [LENGTH_REQUIRED] = "Length Required",
  [PRECONDITION_FAILED] = "Precondition Failed",
  [CONTENT_TOO_LARGE] = "Content Too Large",
  [URI_TOO_LONG] = "URI Too Long",
  [UNSUPPORTED_MEDIA_TYPE] = "Unsupported Media Type",
  [REQUESTED_RANGE_NOT_SATISFIABLE] = "Requested Range Not Satisfiable",
  [EXPECTATION_FAILED] = "Expectation Failed",
  [I_M_A_TEAPOT] = "I'm a teapot",
  [PAGE_EXPIRED__LARAVEL_FRAMEWORK_] = "Page Expired (Laravel Framework)",
  [METHOD_FAILURE__SPRING_FRAMEWORK_] = "Method Failure (Spring Framework)",
  [MISDIRECTED_REQUEST] = "Misdirected Request",
  [UNPROCESSABLE_CONTENT] = "Unprocessable Content",
  [LOCKED] = "Locked",
  [FAILED_DEPENDENCY] = "Failed Dependency",
  [UPGRADE_REQUIRED] = "Upgrade Required",
  [PRECONDITION_REQUIRED] = "Precondition Required",
  [TOO_MANY_REQUESTS] = "Too Many Requests",
  [REQUEST_HEADER_FIELDS_TOO_LARGE] = "Request Header Fields Too Large",
  [LOGIN_TIME_OUT] = "Login Time-out",
  [CONNECTION_CLOSED_WITHOUT_RESPONSE] = "Connection Closed Without Response",
  [RETRY_WITH] = "Retry With",
  [BLOCKED_BY_WINDOWS_PARENTAL_CONTROLS] = "Blocked by Windows Parental Controls",
  [UNAVAILABLE_FOR_LEGAL_REASONS] = "Unavailable For Legal Reasons",
  [REQUEST_HEADER_TOO_LARGE] = "Request Header Too Large",
  [SSL_CERTIFICATE_ERROR] = "SSL Certificate Error",
  [SSL_CERTIFICATE_REQUIRED] = "SSL Certificate Required",
  [HTTP_REQUEST_SENT_TO_HTTPS_PORT] = "HTTP Request Sent to HTTPS Port",
  [INVALID_TOKEN__ESRI_] = "Invalid Token (Esri)",
  [CLIENT_CLOSED_REQUEST] = "Client Closed Request",
  [INTERNAL_SERVER_ERROR] = "Internal Server Error",
  [NOT_IMPLEMENTED] = "Not Implemented",
  [BAD_GATEWAY] = "Bad Gateway",
  [SERVICE_UNAVAILABLE] = "Service Unavailable",
  [GATEWAY_TIMEOUT] = "Gateway Timeout",
  [HTTP_VERSION_NOT_SUPPORTED] = "HTTP Version Not Supported",
  [VARIANT_ALSO_NEGOTIATES] = "Variant Also Negotiates",
  [INSUFFICIENT_STORAGE] = "Insufficient Storage",
  [LOOP_DETECTED] = "Loop Detected",
  [BANDWIDTH_LIMIT_EXCEEDED] = "Bandwidth Limit Exceeded",
  [NOT_EXTENDED] = "Not Extended",
  [NETWORK_AUTHENTICATION_REQUIRED] = "Network Authentication Required",
  [UNKNOWN_ERROR] = "Unknown Error",
  [WEB_SERVER_IS_DOWN] = "Web Server Is Down",
  [CONNECTION_TIMED_OUT] = "Connection Timed Out",
  [ORIGIN_IS_UNREACHABLE] = "Origin Is Unreachable",
  [A_TIMEOUT_OCCURRED] = "A Timeout Occurred",
  [SSL_HANDSHAKE_FAILED] = "SSL Handshake Failed",
  [INVALID_SSL_CERTIFICATE] = "Invalid SSL Certificate",
  [RAILGUN_LISTENER_TO_ORIGIN_ERROR] = "Railgun Listener to Origin Error",
  [ORIGIN_DNS_ERROR] = "Origin DNS Error",
  [NETWORK_READ_TIMEOUT_ERROR] = "Network Read Timeout Error",
};
const char *describe_http_status[] = {
  [CONTINUE] = "The server has received the request headers, and the client should proceed to send the request body.",
  [SWITCHING_PROTOCOLS] = "The requester has asked the server to switch protocols.",
  [PROCESSING] = "This code indicates that the server has received and is processing the request, but no response is available yet. This prevents the client from timing out and assuming the request was lost.",
  [EARLY_HINTS] = "Used to return some response headers before final HTTP message.",
  [OK] = "The request is OK (this is the standard response for successful HTTP requests).",
  [CREATED] = "The request has been fulfilled, and a new resource is created.",
  [ACCEPTED] = "The request has been accepted for processing, but the processing has not been completed.",
  [NON_AUTHORITATIVE_INFORMATION] = "The request has been successfully processed, but is returning information that may be from another source.",
  [NO_CONTENT] = "The request has been successfully processed, but is not returning any content.",
  [RESET_CONTENT] = "The request has been successfully processed, but is not returning any content, and requires that the requester reset the document view.",
  [PARTIAL_CONTENT] = "The server is delivering only part of the resource due to a range header sent by the client.",
  [MULTI_STATUS] = "The message body that follows is by default an XML message and can contain a number of separate response codes, depending on how many sub-requests were made.",
  [ALREADY_REPORTED] = "The members of a DAV binding have already been enumerated in a preceding part of the (multistatus) response, and are not being included again.",
  [THIS_IS_FINE__APACHE_WEB_SERVER_] = "Used as a catch-all error condition for allowing response bodies to flow through Apache when ProxyErrorOverride is enabled.",
  [IM_USED] = "The server has fulfilled a request for the resource, and the response is a representation of the result of one or more instance-manipulations applied to the current instance.",
  [MULTIPLE_CHOICES] = "A link list. The user can select a link and go to that location. Maximum five addresses.",
  [MOVED_PERMANENTLY] = "The requested page has moved to a new URL.",
  [FOUND] = "The requested page has moved temporarily to a new URL.",
  [SEE_OTHER] = "The requested page can be found under a different URL.",
  [NOT_MODIFIED] = "Indicates the requested page has not been modified since last requested.",
  [SWITCH_PROXY] = "No longer used. Originally meant \"Subsequent requests should use the specified proxy.\"",
  [TEMPORARY_REDIRECT] = "The requested page has been temporarily moved to a new URL.",
  [PERMANENT_REDIRECT] = "The requested resource has been permanently moved to a new URL.",
  [BAD_REQUEST] = "The request cannot be fulfilled due to bad syntax.",
  [UNAUTHORIZED] = "The request was a legal request, but the server is refusing to respond to it. For use when authentication is possible but has failed or not yet been provided.",
  [PAYMENT_REQUIRED] = "Not yet implemented by RFC standards, but reserved for future use.",
  [FORBIDDEN] = "The request was a legal request, but the server is refusing to respond to it.",
  [NOT_FOUND] = "The requested page could not be found but may be available again in the future.",
  [METHOD_NOT_ALLOWED] = "A request was made of a page using a request method not supported by that page.",
  [NOT_ACCEPTABLE] = "The server can only generate a response that is not accepted by the client.",
  [PROXY_AUTHENTICATION_REQUIRED] = "The client must first authenticate itself with the proxy.",
  [REQUEST_TIMEOUT] = "The server timed out waiting for the request.",
  [CONFLICT] = "The request could not be completed because of a conflict in the request.",
  [GONE] = "The requested page is no longer available.",
  [LENGTH_REQUIRED] = "The \"Content-Length\" is not defined. The server will not accept the request without it.",
  [PRECONDITION_FAILED] = "The precondition given in the request evaluated to false by the server.",
  [CONTENT_TOO_LARGE] = "The server will not accept the request, because the request entity is too large.",
  [URI_TOO_LONG] = "The server will not accept the request, because the URL is too long. Occurs when you convert a POST request to a GET request with a long query information.",
  [UNSUPPORTED_MEDIA_TYPE] = "The server will not accept the request, because the media type is not supported.",
  [REQUESTED_RANGE_NOT_SATISFIABLE] = "The client has asked for a portion of the file, but the server cannot supply that portion.",
  [EXPECTATION_FAILED] = "The server cannot meet the requirements of the Expect request-header field.",
  [I_M_A_TEAPOT] = "Any attempt to brew coffee with a teapot should result in the error code \"418 I'm a teapot\". The resulting entity body MAY be short and stout.",
  [PAGE_EXPIRED__LARAVEL_FRAMEWORK_] = "Used by the Laravel Framework when a CSRF Token is missing or expired.",
  [METHOD_FAILURE__SPRING_FRAMEWORK_] = "A deprecated response used by the Spring Framework when a method has failed.",
  [MISDIRECTED_REQUEST] = "The request was directed at a server that is not able to produce a response (for example because a connection reuse).",
  [UNPROCESSABLE_CONTENT] = "The request was well-formed but was unable to be followed due to semantic errors.",
  [LOCKED] = "The resource that is being accessed is locked.",
  [FAILED_DEPENDENCY] = "The request failed due to failure of a previous request (e.g., a PROPPATCH).",
  [UPGRADE_REQUIRED] = "The client should switch to a different protocol such as TLS/1.0, given in the Upgrade header field.",
  [PRECONDITION_REQUIRED] = "The origin server requires the request to be conditional.",
  [TOO_MANY_REQUESTS] = "The user has sent too many requests in a given amount of time. Intended for use with rate limiting schemes.",
  [REQUEST_HEADER_FIELDS_TOO_LARGE] = "The server is unwilling to process the request because either an individual header field, or all the header fields collectively, are too large.",
  [LOGIN_TIME_OUT] = "The client's session has expired and must log in again. (IIS)",
  [CONNECTION_CLOSED_WITHOUT_RESPONSE] = "A non-standard status code used to instruct nginx to close the connection without sending a response to the client, most commonly used to deny malicious or malformed requests.",
  [RETRY_WITH] = "The server cannot honour the request because the user has not provided the required information. (IIS)",
  [BLOCKED_BY_WINDOWS_PARENTAL_CONTROLS] = "The Microsoft extension code indicated when Windows Parental Controls are turned on and are blocking access to the requested webpage.",
  [UNAVAILABLE_FOR_LEGAL_REASONS] = "A server operator has received a legal demand to deny access to a resource or to a set of resources that includes the requested resource.",
  [REQUEST_HEADER_TOO_LARGE] = "Used by nginx to indicate the client sent too large of a request or header line that is too long.",
  [SSL_CERTIFICATE_ERROR] = "An expansion of the 400 Bad Request response code, used when the client has provided an invalid client certificate.",
  [SSL_CERTIFICATE_REQUIRED] = "An expansion of the 400 Bad Request response code, used when a client certificate is required but not provided.",
  [HTTP_REQUEST_SENT_TO_HTTPS_PORT] = "An expansion of the 400 Bad Request response code, used when the client has made a HTTP request to a port listening for HTTPS requests.",
  [INVALID_TOKEN__ESRI_] = "Returned by ArcGIS for Server. Code 498 indicates an expired or otherwise invalid token.",
  [CLIENT_CLOSED_REQUEST] = "A non-standard status code introduced by nginx for the case when a client closes the connection while nginx is processing the request.",
  [INTERNAL_SERVER_ERROR] = "An error has occurred in a server side script, a no more specific message is suitable.",
  [NOT_IMPLEMENTED] = "The server either does not recognize the request method, or it lacks the ability to fulfill the request.",
  [BAD_GATEWAY] = "The server was acting as a gateway or proxy and received an invalid response from the upstream server.",
  [SERVICE_UNAVAILABLE] = "The server is currently unavailable (overloaded or down).",
  [GATEWAY_TIMEOUT] = "The server was acting as a gateway or proxy and did not receive a timely response from the upstream server.",
  [HTTP_VERSION_NOT_SUPPORTED] = "The server does not support the HTTP protocol version used in the request.",
  [VARIANT_ALSO_NEGOTIATES] = "Transparent content negotiation for the request results in a circular reference.",
  [INSUFFICIENT_STORAGE] = "The server is unable to store the representation needed to complete the request.",
  [LOOP_DETECTED] = "The server detected an infinite loop while processing the request (sent instead of 208 Already Reported).",
  [BANDWIDTH_LIMIT_EXCEEDED] = "The server has exceeded the bandwidth specified by the server administrator; this is often used by shared hosting providers to limit the bandwidth of customers.",
  [NOT_EXTENDED] = "Further extensions to the request are required for the server to fulfil it.",
  [NETWORK_AUTHENTICATION_REQUIRED] = "The client needs to authenticate to gain network access.",
  [UNKNOWN_ERROR] = "The 520 error is used as a \"catch-all response for when the origin server returns something unexpected\", listing connection resets, large headers, and empty or invalid responses as common triggers.",
  [WEB_SERVER_IS_DOWN] = "The origin server has refused the connection from Cloudflare.",
  [CONNECTION_TIMED_OUT] = "Cloudflare could not negotiate a TCP handshake with the origin server.",
  [ORIGIN_IS_UNREACHABLE] = "Cloudflare could not reach the origin server; for example, if the DNS records for the origin server are incorrect.",
  [A_TIMEOUT_OCCURRED] = "Cloudflare was able to complete a TCP connection to the origin server, but did not receive a timely HTTP response.",
  [SSL_HANDSHAKE_FAILED] = "Cloudflare could not negotiate a SSL/TLS handshake with the origin server.",
  [INVALID_SSL_CERTIFICATE] = "Used by Cloudflare and Cloud Foundry's gorouter to indicate failure to validate the SSL/TLS certificate that the origin server presented.",
  [RAILGUN_LISTENER_TO_ORIGIN_ERROR] = "Error 527 indicates that the request timed out or failed after the WAN connection had been established.",
  [ORIGIN_DNS_ERROR] = "Error 530 indicates that the requested host name could not be resolved on the Cloudflare network to an origin server.",
  [NETWORK_READ_TIMEOUT_ERROR] = "Used by some HTTP proxies to signal a network read timeout behind the proxy to a client in front of the proxy.",
};
enum http_status parse_http_status(s8 s) {
  for (size i = 0; i < 85; i++)
    if(s8equal(s, s8wrap(spell_http_status[i], 1024)))
      return (enum http_status)i;
  return (enum http_status)0;
}
enum content_type {
  INVALID_CONTENT_TYPE,
  HTML,
};
const char *spell_content_type[] = {
  [HTML] = "html",
};
const char *describe_content_type[] = {
  [HTML] = "text/html; charset=UTF-8",
};
enum content_type parse_content_type(s8 s) {
  for (size i = 0; i < 1; i++)
    if(s8equal(s, s8wrap(spell_content_type[i], 1024)))
      return (enum content_type)i;
  return (enum content_type)0;
}
#endif // HTTP_CODES_JSON
